### ISSUE TITLE
Template provisioning consistently fails

### ISSUE THREAD

**Issue by jaredfholgate** [SharePoint/sp-provisioning-service#417] opened 2021-03-11 13:02 UTC
**Describe the issue**
Whenever I try to provision a look book, it consistently fails with this message;

Sorry, something went wrong
There was an unexpected issue.
Cannot retrieve a valid Access Token for user jared.holgate@m***s.com in tenant 93c****-ed89-4fa6-80cf-b0a********4

**Expected behavior**
It provisions the look book

**Screenshots**
![image](https://user-images.githubusercontent.com/1612200/110791038-abc62a80-8269-11eb-8ffa-85e223446c97.png)

**Details (please complete the following information):**
- PnP Correlation ID: appId=cid-v1:ccc54f05-096c-4a72-a440-e7a8bfdf2d39
- Reference Template: https://lookbook.microsoft.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
- Primary language of the target tenant: UK?
- Are you using a Tenant Global Admin account to provision the template: Yes

**Additional context**

**Comment by PaoloPia** [comment] 2021-03-12 09:10
Hi,
Thanks for using the Look Book site. Based on the exception that you see, the problem is that the Provisioning App can't retrieve a valid access token for consuming the Microsoft Graph. Reasons could be:
1) The grant/consent process for the app didn't go well. If this is the case, you can try to delete the app with name "SharePointPnP.ProvisioningApp.Tenant" from the Enterprise Applications in your Azure Active Directory and re-start from scratch the provisioning process.
2) There is something like Client Access Policies or MFA blocking the request to acquire an access token for Microsoft Graph.
Can you eventually see if, using the Microsoft Graph Explorer(https://developer.microsoft.com/en-us/graph/graph-explorer) and with the same tenant and user account, you can access the Microsoft Graph or not? You can for example make a request for https://graph.microsoft.com/v1.0/sites/root.

Please, let me know.

Thanks.

**Comment by PaoloPia** [comment] 2021-04-19 06:34
Hi,
Thanks for using the Look Book site. I'm going to close this item because you did not reply back after 25 days. Please, feel free to try again the template and to create another issue, providing the Correlation ID of the request, for further investigation. Thanks for your feedback.

**Closed by PaoloPia** 2021-04-19 06:34 UTC
Labels: template-issue, waiting-for-clarification
