### ISSUE TITLE
365 Learning Pathways Provisioning Issues

### ISSUE THREAD

**Issue by nirmala-m** [SharePoint/sp-provisioning-service#184] opened 2020-03-04 14:58 UTC
## Category

- [x] Bug

## Describe the bug

> We tried to provision the 365 Learning Pathways in our PROD and we ran into provisioning error immediately once we click the "Add to your tenant". The person who tried provisioning has logged in to their global admin account and also has administrator permissions in the Tenant App Catalog.

## Steps to reproduce

>1.  Sign into tenant as tenant admin.
>2.   Go to the Microsoft 365 learning pathways solution page: https://provisioning.sharepointpnp.com/details/3df8bd55-b872-4c9d-88e3-6b2f05344239
 >3.   Click Add to your tenant. The very first time when we tried , it did asked for "Consent on behalf of the organization to provision the app" .
We did not get the screen to provide consent when we tried subsequent trials
>4. See error -
Sorry, something went wrong. There was an unexpected issue. Please try again after a while.
Current site is not a tenant administration site.
## Expected behavior

>We should see the provision information screen which would get Email address, destination URL's and provision button to install the Learning Pathways into the Tenant App catalog.

## Developer environment

- OS: Windows 10
- Browser(s): Chrome v80, Internet Explorer 11

### Additional context

![PROD_ERROR](https://user-images.githubusercontent.com/51378965/75892011-a59fa180-5dfe-11ea-9bc9-66090bb3336c.PNG)

**Comment by nirmala-m** [comment] 2020-03-16 13:41
Hello team 
Any updates on this case, please?

**Comment by misterjasonwong** [comment] 2020-04-12 09:07
@nirmala-m I just provisioned successfully. Had issues earlier on in the day. Perhaps the guys have addressed the provisioning issue.

**Comment by nielsimmink** [comment] 2020-05-08 10:11
Hi,

I can reproduce the same issue as @nirmala-m on my tenant, both using the look book and the learning pathways. I have a test tenant where both the look books and the learning pathways get provisioned correctly. on of the big differences between the 2 tenabts is that the failing tenant has a vanity domain (companyname.com), where the second is a regular companyname.sharepoint.com tenant.
HTH

Niels

**Comment by PaoloPia** [comment] 2020-08-05 20:34
Hi, Thanks for your feedback. I'm closing this item because it is now outdated.

**Closed by PaoloPia** 2020-08-05 20:34 UTC
